# Site settings
title: FAB16 Montreal
email: fab16@fabfoundation.org
description: > # this means to ignore newlines until "baseurl:"
    The annual gathering of the global Fablab Network, including representatives of more than 1700 labs around the world
baseurl: "/FAB16/splash" # the subpath of your site, e.g. /blog/
#url: "https://splash.fab16.org" # the base hostname & protocol for your site

twitter_username: "fab16"
github_username: "fab16"

# Build settings
markdown: kramdown
exclude: ["README.md", "LICENSE"]
