# Site settings
defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

title: FAB16 Montreal
email: fab16@fabfoundation.org
description:
    The annual gathering of the global Fablab Network, including representatives of more than 1700 labs around the world

image:
    width: 1200
    height: 630
en:
  image:
    path: "/assets/img/Fab16_facebookbanner_EN.jpg"
  description:
    The annual gathering of the global Fablab Network, including representatives of more than 1800 labs around the world
fr:
  image:
    path: "/assets/img/Fab16_facebookbanner_FR.jpg"
  description:
    Le rassemblement annuel du réseau mondial Fablab, comprenant des représentants de plus de 1800 labs à travers le monde

google_analytics: UA—XXXXXXXX-X

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fab16.org"

twitter_username: "fab16"
twitter_link: "https://twitter.com/FAB16Montreal"
facebook_username: "fab16"
facebook_link: "https://www.facebook.com/FAB16Montreal/"
instagram_username: "fab16"
instagram_link: "https://www.instagram.com/fab16montreal/"
youtube_username: "fab16"
youtube_link: "https://www.youtube.com/playlist?list=PLzbfnp3WeXMEk446utFOzSqo1XYlvwa7h"
github_username: "fab16"
github_link: "fab16"

# Build settings
markdown: kramdown
exclude: ["README.md", "LICENSE"]

