en:
  title   : "Participate"
  img     : "assets/img/applications.png"
  subtitle: "How to participate"
  text    : "FAB16 will integrate all the knowledge gained during the year by more than 2000 Fab Labs around the world. 
            At this conference, everyone is invited to participate in various activities: proposing, leading or getting involved in a workshop or working group, submitting research publications, becoming a volunteer, just to name a few. 
            The Regional Networks are gathering their communities to participate in online and local events as FAB16 Hubs. 
            To see a list of all of the FAB16 Hubs and get involved with your local Hub, click <a href='/program'>here</a>!
            <br><br>
            Click the links below to learn more."

  application:
    #- item      : "item1"
    #  menu      : "Working groups"
    #  title     : "Participate with your working groups"
    #  text      : "Join us in the Working Groups of the Fab Labs Network, where we gather in smaller cohorts to plan out recurring global initiatives, such as Fab Academy, International Education, Assistive Technology, and more.<br>
    #              These are theoretical discussions, and a chance for the global community to connect and share their perspectives.
    #              <br><br>
    #              Use the link below to submit a working group!"
    #  buttontext: "Coming soon"
    #  modal     : ""
    #  link      : "https://conf.fabevent.org/users/sign_in?conference_acronym=Fab16&locale=en"

    - item      : "item1"
      menu      : "Workshops"
      title     : "Participate with your workshops"
      text      : "Whether you're new to a FABx conference or have attended many, workshops are a great way to share your knowledge with the Fab Lab network. 
                  Workshops are either theoretical or hands-on, and cover a wide range of topics, from biomaterials to hacking a machine to Sustainable Development Goals. 
                  Workshop facilitators are community members who come with prior experience in their local community projects, workshops, and ideas. 
                  They can be new or active members of the Fab Lab network!  
                  <br><br>
                  Use the link below to propose a workshop! 
                  <br><br>
                  <em>** Keep in mind that your workshop should be no longer than 2 hours. 
                  Most people will join online and, given the circumstances surrounding Covid-19, not everyone will have access to the tools found in a Fab Lab unless they can purchase them in advance. 
                  So we need to be creative!</em>"
      buttontext: "Participate"
      buttonclass: ""
      modal     : ""
      link      : "https://forms.gle/SNM7pvtJzjYEyWAU9"

    - item      : "item2"
      menu      : "Research papers"
      title     : "Submit your scientific paper "
      text      : "The research paper stream of FAB16 invites authors of original research articles studying the Fab Lab movement, its ambitions and impacts across a broad spectrum of disciplines, including computer science, engineering, science and technology fields, management and business, education, urban planning, media and design, and more. 
                  Use the link below to submit a publication:
                  <br><br>
                  <em>Abstract Submission Deadline: May 31, 2021</em>"
      buttontext: "Participate"
      buttonclass: ""
      modal     : ""
      link      : "https://easychair.org/cfp/Fab16"

    - item      : "item3"
      menu      : "FAB16 Challenges"
      title     : "Stop. Reboot. Learn: Innovating Fab teaching and learning for the next decade"
      text      : "This FAB16 award challenge, sponsored by Dassault Systemes SOLIDWORKS and the 3DEXPERIENCE Lab, gives you the chance to think big, and to envision new ways of fab teaching and learning over the next decade. 
                  Tell us your visionary idea or give a concrete example of a physical product that will reboot learning.
                  <br><br>
                  <em>Apply here by Wednesday, August 4 :</em>"
      buttontext: "Apply"
      buttonclass: ""
      modal     : ""
      link      : "https://forms.gle/TnpU45DCJHbPvXpw5"

    - item      : "item4"
      menu      : "FAB World and More"
      title     : "Participate with FAB World, Fabercise, Fab Cinema and more!"
      text      : "We want to know what projects you and your community are developing! 
                  This is your opportunity during FAB16 to give a 3-minute presentation to the community about projects, initiatives, your teams, and developments that are happening in your Fab Lab and community. 
                  This year, in addition to Fab World, we are also encouraging the Fab Lab network to submit other pre-recorded creative content, such as to run a Fabercise, propose a Fab Cinema, a &ldquo; Fab Discovery &rdquo; and/or a Podcast! 
                  Teach the network something new! 
                  You can find a description of each of these in the application form.
                  <br><br>
                  Keep in mind that this year's theme is &ldquo;Fabricating the Commons,&rdquo; and it's about how we can produce and share knowledge and tools based on peer production to create a sustainable future for all.
                  <br><br>
                  Want to share your initiatives? Use the link below to submit your proposals! "
      buttontext: "Participate"
      buttonclass: "border-white"
      modal     : ""
      link      : "https://forms.gle/oiHMkjfDiYtHgqvcA"

    - item      : "item5"
      menu      : "Fab Festival"
      title     : "Organize a workshop at the Fab Festival local event"
      text      : "The Fab Festival is an all-Saturday event open to a local public in Montréal.
                  Free workshops where children, young and old will have the opportunity to have their first experience with digital fabrication methodologies.
                  An event that you certainly can't miss!
                  <br><br>
                  If you want to lead a workshop during the Fab Festival, write to us at  <a href='mailto:fab16@fabfoundation.org' class='btn' style='float:unset;'>fab16@fabfoundation.org</a>"
      buttontext: ""
      buttonclass: ""
      modal     : ""
      link      : ""

    - item      : "item6"
      menu      : "Become a volunteer"
      title     : "Becoming a volunteer means ..."
      text      : "<ul class='colorwhite'>
                    <li>Being in contact with people from different cultures</li>
                    <li>Supporting participants during the conference by facilitating their experience</li>
                    <li>Creating links with other volunteers and actors of the movement.</li>
                  </ul>
                  <p class='colorwhite'>
                  Given the circumstances of COVID-19, we do not yet know whether we will be able to host international participants in person in Montréal. 
                  <b>Our current volunteer application form is only for people who currently live in Canada and plan to attend FAB16 in person.</b>
                  <br><br>
                  In the coming months, we will be reaching out to the Fab Lab Network about volunteering for the international ONLINE event. 
                  <br><br>
                  This is an opportunity for you to be a part of the largest digital fabrication event in the world!
                  <br><br>
                  Use the link below to submit your interest! 
                  <br><br>
                  <em>**You have to be authorized by the Canadian government to legally work as a volunteer in Montréal.</em>
                  </p>"
      buttontext: "Participate"
      buttonclass: ""
      modal     : ""
      link      : "https://forms.gle/L32rN6jNKnZCoNCk6"
    
    - item      : "item7"
      menu      : "Become a sponsor"
      title     : "Becoming a sponsor is …"
      text      : "<ul class='colorwhite'>
                    <li>An opportunity to be a leader in disruptive technologies like 3D Printing, CAD design, robotics, laser machining and more!</li>
                    <li>Create a spirit of collaboration between makers from around the world to advance complex projects.</li>
                    <li>Connect with leaders who are using digital fabrication as a way to make breakthroughs in various fields.</li>
                    <li>Bring your brand or products and services to a creative audience that uses a wide variety of hardware and software.</li>
                  </ul>
                  <p class='colorwhite'>
                  Contact us to find out how you can take part in this extraordinary event and secure your participation, at <a href='mailto:fab16@communautique.quebec' class='btn' style='float:unset;'>fab16@communautique.quebec</a> 
                  </p>"
      buttontext: ""
      modal     : ""
      link      : ""

fr:
  title   : "Participer"
  img     : "assets/img/applications.png"
  subtitle: "Comment participer"
  text    : "FAB16 intégrera toute la connaissance acquise durant l’année par plus de 2000 Fab Labs à travers le monde.
            Lors de notre rencontre à cette conférence, tout le monde est invité à participer à diverses activités : animer ou s’impliquer dans un atelier ou groupe de travail, soumettre ses publications de recherche, devenir bénévole, pour n'en citer que quelques-unes.
            Les réseaux régionaux rassemblent leurs communautés pour participer à des événements en ligne et locaux en tant que Hubs FAB16. 
            Pour voir la liste de tous les Hubs FAB16 et vous impliquer dans votre Hub local, cliquez <a href='/programme'>ici</a> !
            <br><br>
            Visitez les onglets ci-bas pour participer!"

  application:
    #- item      : item1
    #  menu      : "Groupes de travail"
    #  title     : "Participez aux groupes de travail"
    #  text      : "Prenez part aux groupes de travail du réseau des Fab Labs, où nous nous réunissons en petites cohortes afin de planifier les initiatives mondiales récurrentes comme la Fab Academy, l’éducation internationale, les technologies d’assistance, et plus.<br>
    #              Ces discussions théoriques sont une chance pour la communauté globale de se connecter ensemble et de partager leurs perspectives. 
    #              <br><br>
    #              Utilisez le lien ci-dessous pour soumettre un groupe de travail!
    #              "
    #  buttontext: "À venir"
    #  modal     : ""
    #  link      : "https://conf.fabevent.org/users/sign_in?conference_acronym=Fab16&locale=en"
    
    - item      : item1
      menu      : "Ateliers"
      title     : "Participez avec vos ateliers"
      text      : "Que vous soyez novice en matière d'événements FABx ou que vous ayez déjà participé à de nombreux événements, les ateliers sont un excellent moyen de partager vos connaissances avec le réseau des Fab Labs. 
                  Les ateliers sont soit théoriques, soit pratiques, et couvrent un large éventail de sujets, allant des biomatériaux au piratage d'une machine en passant par les objectifs de développement durable. 
                  Les animateurs des ateliers sont des membres de la communauté qui arrivent avec une expérience préalable des projets, ateliers et idées de leur communauté locale. 
                  Ils peuvent être des membres nouveaux ou actifs du réseau Fab Lab ! 
                  <br><br>
                  Utilisez le lien ci-dessous pour proposer un atelier ! 
                  <br><br>
                  <em>**Gardez à l'esprit que votre atelier ne doit pas durer plus de 2 heures. 
                  La majorité des personnes se joindront en ligne et, étant donné les circonstances entourant Covid-19, tout le monde n'aura pas accès aux outils que l'on trouve dans un Fab Lab, à moins de pouvoir les acheter à l'avance. 
                  Nous devons donc être créatifs !</em>"
      buttontext: "Participer"
      buttonclass: ""
      modal     : ""
      link      : "https://forms.gle/yHsZeu3WEP1f5dBv8"
    
    - item      : item2
      menu      : "Publications scientifiques"
      title     : "Soumettez votre publication scientifique"
      text      : "Le volet du FAB16 concernant les papiers de recherche invite les auteurs d’articles de recherche originaux étudiant le mouvement Fab Lab, ses ambitions et ses impacts au travers d’un large spectre de disciplines, incluant les sciences informatiques, l’ingénierie, les domaines scientifiques et technologiques, la gestion et les affaires, l’éducation, l’urbanisme, les médias et le design, et bien d’autres encore.
                  Utilisez le lien ci-dessous pour soumettre une publication:
                  <br><br>
                  <em>Date limite d'inscription des résumés : 31 mai 2021</em>"
      buttontext: "Participez"
      buttonclass: ""
      modal     : ""
      link      : "https://easychair.org/cfp/Fab16"
    - item      : item3
      menu      : "FAB16 Challenge"
      title     : "Stop. Redémarrez. Apprendre : Innover dans la Fab formation et apprentissage pour la prochaine décennie"
      text      : "Ce concours FAB16, parrainé par Dassault Systèmes SOLIDWORKS et le 3DEXPERIENCE Lab, vous donne l'occasion de voir grand et d'imaginer de nouvelles façons d'enseigner et d'apprendre dans les Fab Lab au cours de la prochaine décennie. 
                  Faites-nous part de votre idée visionnaire ou donnez un exemple concret d'un produit concret qui va redynamiser l'apprentissage.
                  <br><br>
                  <em>Posez votre candidature ici avant le mercredi 4 août :</em>"
      buttontext: "Participez"
      buttonclass: ""
      modal     : ""
      link      : "https://forms.gle/TnpU45DCJHbPvXpw5"
    
    - item      : item4
      menu      : "FAB World et plus"
      title     : "Participez à FAB World, Fabercise, Fab Cinéma et plus encore !"
      text      : "Nous voulons savoir quels sont les projets que vous et votre communauté développez dans votre Fab Lab ! 
                  C'est l'occasion, pendant le FAB16, de présenter un exposé de 3 minutes auprès de la communauté sur des projets, des initiatives, vos équipes et les développements qui ont lieu dans votre Fab Lab et votre collectivité. 
                  Cette année, en plus du Fab World, nous encourageons également le réseau des Fab Labs à soumettre d'autres contenus créatifs préenregistrés, tels que pour diriger un Fabercise, proposer un Fab Cinéma, un &ldquo; Fab Discovery &rdquo; et/ou un Podcast ! Apprenez au réseau quelque chose de nouveau ! 
                  Vous trouverez une description de chacun d'entre eux dans le formulaire d'application.
                  <br><br>
                  Gardez à l'esprit que le thème de cette année est  &ldquo;Fabricating the Commons&rdquo;,  et qu'il s'agit de voir comment nous pouvons produire et partager des connaissances et des outils basés sur la production par les pairs afin de créer un avenir durable pour tous.
                  <br><br>
                  Vous souhaitez partager vos initiatives ? Utilisez le lien ci-dessous pour soumettre vos propositions !"
      buttontext: "Participer"
      buttonclass: "border-white"
      modal     : ""
      link      : "https://forms.gle/XBPgvb9JcWUDfwhr5"
    
    - item      : item5
      menu      : "Fab Festival"
      title     : "Organisez un atelier local lors de l'événement local Fab Festival "
      text      : "Le Fab Festival est un événement d’une journée, le samedi, ouvert au public local à Montréal.
                  <br>
                  Des ateliers gratuits où les enfants, les jeunes et les moins jeunes auront la possibilité d'avoir leur première expérience des méthodologies de fabrication numérique.<br>
                  Un événement que vous ne pourrez certainement pas manquer !
                  <br><br>
                  Si vous souhaitez animer un atelier durant le Fab Festival, écrivez-nous à <a href='mailto:fab16@fabfoundation.org' class='btn' style='float:unset;'>fab16@fabfoundation.org</a>"
      buttontext: ""
      buttonclass: ""
      modal     : ""
      link      : ""
    
    - item      : item6
      menu      : "Devenez bénévole"
      title     : "Devenir bénévole c'est ..."
      text      : "<ul class='colorwhite'>
                    <li>Être en contact avec des gens de différentes cultures</li>
                    <li>Soutenir les participants durant la conférence en facilitant leur expérience</li>
                    <li>Créer des liens avec d’autres bénévoles et acteurs du mouvement.</li>
                  </ul>
                  <p class='colorwhite'>
                  Compte tenu des circonstances de COVID-19, nous ne savons pas encore si nous serons en mesure d'accueillir en personne des participants internationaux à Montréal. 
                  <b>Notre formulaire actuel de bénévolat ne s'adresse qu'aux personnes qui vivent actuellement au Canada et qui prévoient d'assister en personne au FAB16. </b>
                  <br><br>
                  Dans les mois à venir, nous contacterons le Réseau des Fab Labs au sujet du bénévolat pour l'événement international EN LIGNE. 
                  <br><br>
                  C'est une opportunité pour vous de faire partie du plus grand événement de fabrication numérique au monde !
                  <br><br>
                  Utilisez le lien ci-dessous pour soumettre votre intérêt ! 
                  <br><br>

                  <em>**Vous devez être autorisé par le gouvernement canadien à travailler légalement comme bénévole à Montréal.</em>
                  </p>"
      buttontext: "Participer"
      buttonclass: ""
      modal     : ""
      link      : "https://forms.gle/pMrMGEGyfN4ZRhKN7"
    
    - item      : item7
      menu      : "Devenez commanditaire"
      title     : "Devenir commanditaire c’est …"
      text      : "<ul class='colorwhite'>
                    <li>Une occasion d’être un chef de file dans les domaines des technologies de rupture comme l’impression 3D, la conception CAO, la robotique, l’usinage laser et plus encore.</li>
                    <li>Créez un esprit de collaboration entre les fabricants du monde entier pour faire avancer des projets complexes.</li>
                    <li>Communiquez avec des chefs de file qui utilisent la fabrication numérique comme moyen de faire des percées dans divers domaines.</li>
                    <li>Faites connaître votre marque ou vos produits et services à un public créatif qui utilise une grande variété de matériel et de logiciels.</li>
                  </ul>
                  <p class='colorwhite'>
                  Contactez-nous pour trouver comment vous pouvez prendre part à cet extraordinaire événement et assurer votre participation, en nous écrivant à <a href='mailto:fab16@communautique.quebec' class='btn' style='float:unset;'>fab16@communautique.quebec</a>
                  </p>"
      buttontext: ""
      buttonclass: ""
      modal     : ""
      link      : ""